### ISSUE TITLE
Android not connecting.

### ISSUE THREAD

**Issue by bradintheusa** [VNAPNIC/flutter_nearby_connections#1]
Hi,

I was able to able to get the sample iOS working but the android I could not.  Should android work and should cross platform work?  If the answer is yes I can dig in further or help out.

Brad

**Comment by VNAPNIC** [comment]
can u use-package: `https://pub.dev/packages/nearby_connections` for android os

**Comment by bradintheusa** [comment]
Thanks for the response. Mush appreciated.

**Comment by VNAPNIC** [comment]
Fixed in the version https://github.com/VNAPNIC/flutter_nearby_connections/releases/tag/1.0.0
