### ISSUE TITLE
Android example not working

### ISSUE THREAD

**Issue by bradintheusa** [VNAPNIC/flutter_nearby_connections#10]
Hi

I can get the ios sample working fine.   If I try the Android it does not.  I've used 2 physical devices (Nexus 5x) and a pair of simulators (Pixel 4) without luck.

I see this in the status bar on each Pixel 4 device.

![Untitled](https://user-images.githubusercontent.com/1160356/99987947-0b61fe00-2d7f-11eb-8f9e-b575337ba949.png)

**Comment by VNAPNIC** [comment]
android don't support emulator

**Comment by bradintheusa** [comment]
Thanks.  I tried on physical Android devices but will try again.  They need to both be android right? No cross platform?
