### ISSUE TITLE
No code for file sharing 

### ISSUE THREAD

**Issue by JanviPatel1310** [VNAPNIC/flutter_nearby_connections#11]
There is no code for file-sharing can anyone please provide it for this plugin will be really appericiated
Thanks in advance

**Comment by bspriggs99** [comment]
Just to add to this, is it currently only possible to send messages via this p2p plugin, or is it possible to send other data types other than STRING such as sending an image?

**Comment by VNAPNIC** [comment]
u can convert image into byte array and byte array to base64 String

like that:

```
List<int> imageBytes = widget.fileData.readAsBytesSync();
print(imageBytes);
String base64Image = base64Encode(imageBytes);
```

**Comment by VNAPNIC** [comment]
> u can convert image into byte array and byte array to base64 String
> 
> like that:
> 
> ```
> List<int> imageBytes = widget.fileData.readAsBytesSync();
> print(imageBytes);
> String base64Image = base64Encode(imageBytes);
> ```
