### ISSUE TITLE
How to use this without Google Play Service?

### ISSUE THREAD

**Issue by naiba** [VNAPNIC/flutter_nearby_connections#12]
Hi there, Could we use this without Google Play Service?

**Comment by naiba** [comment]
I mean just use WI-FI_P2P without nearby api.

**Comment by VNAPNIC** [comment]
We're developing the feature but now we have stopped because it is not feasible
https://github.com/VNAPNIC/flutter_nearby_connections/tree/feature/integrate-android-wifi-p2p
