### ISSUE TITLE
Using custom DeviceName in nearbyService.init

### ISSUE THREAD

**Issue by SKnoedler** [VNAPNIC/flutter_nearby_connections#13]
Hello there:) Is it possible to define the device name so that other devices see this name when I am discovered?
I've tried a string within nearbyService.init(DeviceName: "..."   but the name of the discovered device has only been "Unknown".

**Comment by VNAPNIC** [comment]
Android or IOS?

**Comment by SKnoedler** [comment]
I've only tested it on android using xiaomi mi 9t connecting to xiaomi redmi note 9 pro. I'll try a different device soon.
