### ISSUE TITLE
Null Safety

### ISSUE THREAD

**Issue by stonekase** [VNAPNIC/flutter_nearby_connections#15]
Hi, Thank you for the great work you are doing. Please any plans for null-safety as this is the future of flutter ?

**Comment by cor277** [comment]
i have same problem.
iàm downloading the source and try to apply null safety. If this work do better, i try to push code.

**Comment by VNAPNIC** [comment]
yup, i will update it

**Comment by VNAPNIC** [comment]
> > yup, i will update it
> 
> If you want we can work on null safety and share you the code, or we can do a branch in github

I will add you to the project as a contributor

**Comment by cor277** [comment]
Null safety committed.

also, i found there is android registration is obsolete in kt files. are you able to change?

**Comment by cor277** [comment]
@VNAPNIC you have to update pub.dev to project is null safety

**Comment by Sford4** [comment]
@cor277 @VNAPNIC Is the null safety released? Should we all update to the newest version? 

Thank you for all your work!

**Comment by VNAPNIC** [comment]
updated
https://pub.dev/packages/flutter_nearby_connections/versions/1.0.11

**Comment by VNAPNIC** [comment]
https://pub.dev/packages/flutter_nearby_connections/versions/1.0.11
