### ISSUE TITLE
Wrong deviceId

### ISSUE THREAD

**Issue by mgeilich** [VNAPNIC/flutter_nearby_connections#17]
On receipt of a message from a peer, the Message contains deviceId and message.  The deviceId is incorrect - it is the ID of the receiver of the message when it should be the deviceId of the sender.  As far as I can tell, there is no way to determine the ID of the sender of a Message.

**Comment by 7anya** [comment]
hey so, i sent messages from 1 device to 2 other devices and the deviceID was same in the messages received on both devices. thus the deviceId shown is the device id of the sender not the reciever

**Comment by VNAPNIC** [comment]
Closed https://github.com/VNAPNIC/flutter_nearby_connections/issues/20
