### ISSUE TITLE
Example App does not work on Samsung Galaxy A40 / Samsung Galaxy Tab A

### ISSUE THREAD

**Issue by mbalmer** [VNAPNIC/flutter_nearby_connections#2]
I build the example app using Flutter 1.22 and loaded it to a Samasung Galaxy A40 phone and a Samsung Galaxy Tab A tablet.  Both devices are in the same WLAN and Bluetooth is enabled.

The devices do not see each other, the example app does not list in "Browser"-mode the other device that is in "Advertise"-mode.

**Comment by VNAPNIC** [comment]
we're developing for Android OS 
can u. follow the progress in here 
https://github.com/VNAPNIC/flutter_nearby_connections/projects/1#card-47192201

**Comment by mbalmer** [comment]
Oh, now I understand, I mistakenly thought it would already run on Android.  Of course I will watch the progress.

Many thanks!

**Comment by VNAPNIC** [comment]
Fixed in the version https://github.com/VNAPNIC/flutter_nearby_connections/releases/tag/1.0.0

**Comment by mbalmer** [comment]
I just tested this on both devices and it seems to work now on Android.  Thanks!
