### ISSUE TITLE
DeviceId of the device the app is installed on

### ISSUE THREAD

**Issue by 7anya** [VNAPNIC/flutter_nearby_connections#20]
How can on find the deviceID of the device the app is installed on. For example i want the device id of my own phone through the app, how may i do that?

**Comment by VNAPNIC** [comment]
I don't support getting my own device's id, because android can't support it,
you can use deviceName to identify the connected device

`
nearbyService.invitePeer( deviceID: device.deviceId,  deviceName: device.deviceName);
`

**Comment by 7anya** [comment]
Thank you for your clarification. Helps a lot :)
