### ISSUE TITLE
The Example app stops working after I updated the device to androd 12.

### ISSUE THREAD

**Issue by sasikdar** [VNAPNIC/flutter_nearby_connections#29]
The Example app stopped working right after I updated the app to andriod 12. 
I was using two google pixel 4A. I updated one of them to Andriod 12 and then the I needed to add the andriod:exported parameter in Manifest. and after installing the app new the browsing or the advertising is not working. The other phone can not discover the device anymore. The device would vibrate or notify everytime I clicked on brower or advertisement. But now it is not doing that either. 

This could be a great help if someone could help me regarding this.

**Comment by VNAPNIC** [comment]
@sasikdar 
update android 12
You must add these 2 permissions to your app
<uses-permission android:name="android.permission.BLUETOOTH_SCAN" />
<uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />
Manifest.permission.BLUETOOTH_SCAN, Manifest.permission.BLUETOOTH_CONNECT
