### ISSUE TITLE
Example app crashes (or terminates) on iPhone 11 Pro Max

### ISSUE THREAD

**Issue by mbalmer** [VNAPNIC/flutter_nearby_connections#3]
I am running the example app on an iPhone 11 Pro Max, the app launches, but when tapping ether "BROWSER" or "ADVERTISER", the app terminates immediately.

**Comment by mbalmer** [comment]
The example app shows the same behaviour on an iPod touch 7th generation.

**Comment by VNAPNIC** [comment]
ok , let me check.
send me ur error

**Comment by VNAPNIC** [comment]
ok, let me check.
Please add your error log

**Comment by mbalmer** [comment]
How can I find the log?  The console in Android studio only prints "Lost connection to device".

**Comment by VNAPNIC** [comment]
u can run on Xcode.

**Comment by mbalmer** [comment]
2020-10-12 14:27:36.735015+0200 Runner[443:21874] -[flutter_nearby_connections.MPCManager browser:didNotStartBrowsingForPeers:]: unrecognized selector sent to instance 0x281d01cc0
2020-10-12 14:27:36.735221+0200 Runner[443:21874] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[flutter_nearby_connections.MPCManager browser:didNotStartBrowsingForPeers:]: unrecognized selector sent to instance 0x281d01cc0'
*** First throw call stack:
(0x18b9e7114 0x19f20dcb4 0x18b8f79b8 0x18b9e9494 0x18b9eb6cc 0x1032e3db8 0x1032e55fc 0x1032f3a6c 0x18b966c30 0x18b9610e8 0x18b960200 0x1a1a5b598 0x18e226004 0x18e22b5d8 0x100f69b68 0x18b63f598)
libc++abi.dylib: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[flutter_nearby_connections.MPCManager browser:didNotStartBrowsingForPeers:]: unrecognized selector sent to instance 0x281d01cc0'
terminating with uncaught exception of type NSException
(lldb)

**Comment by VNAPNIC** [comment]
Fixed in the version https://github.com/VNAPNIC/flutter_nearby_connections/releases/tag/1.0.0
