### ISSUE TITLE
Not working on android devices

### ISSUE THREAD

**Issue by yossefEl** [VNAPNIC/flutter_nearby_connections#4]
Hi @VNAPNIC 
First, thanks for taking the time to develop this plugin!
I tested this plugin on physical devices And I found that:
#### Works in case of
iOS to iOS
#### Doesn't wok in case of
Android to android
Android to iOS
Also the plugin is not requesting **Nearby permission**
I found also that the app requires the **location permission** but it doesn't ask for it , so I tried to **authorize it manually but it doesn't fix the issue**

**Comment by VNAPNIC** [comment]
I will update for Android, but can't make a connection between Android and IOS
u can follow progress android in the https://github.com/VNAPNIC/flutter_nearby_connections/projects/1

**Comment by yossefEl** [comment]
I got it, thank you so much @VNAPNIC, waiting for the next update ❤️

**Comment by aymane6** [comment]
Hi @VNAPNIC 
Are you going to update the framework to allow communication between ios and android soon?

**Comment by TJMusiitwa** [comment]
@aymane6 The underlying technologies that make up nearby connections on Android and iOS differ and as such make it impossible to communicate between the two platforms therefore, communication or sharing can only be done on the respective platforms and not inter-platform.

**Comment by VNAPNIC** [comment]
Fixed in the version https://github.com/VNAPNIC/flutter_nearby_connections/releases/tag/1.0.0
