### ISSUE TITLE
Adopt/Merge with nearby_connections to work inside the package

### ISSUE THREAD

**Issue by TJMusiitwa** [VNAPNIC/flutter_nearby_connections#5]
Hello there, this is a great plugin and is just what I needed for an upcoming project but was lacking on the iOS side. However, it seems as though you are lacking the Android implementation of nearby_connections. Good thing though that there is a developer who has already done extensive work into a similar package like this but for Android only and is looking to have an iOS implementation => [nearby_connections](https://github.com/mannprerak2/nearby_connections)

Perhaps you could reach out to him and try to see if there is a way to merge the two plugins into one as it is possible it could save you some considerable development time.

**Comment by VNAPNIC** [comment]
The Android [near_connections](https://github.com/mannprerak2/nearby_connections) only support Bluetooth, so we don't integrate, we developing for android, maybe next version.

**Comment by TJMusiitwa** [comment]
Oh okay then...looking forward to it then..

**Comment by VNAPNIC** [comment]
Fixed in the version https://github.com/VNAPNIC/flutter_nearby_connections/releases/tag/1.0.0
