### ISSUE TITLE
Value of optional type String? (deviceId) must be unwrapped

### ISSUE THREAD

**Issue by pharshdev** [VNAPNIC/flutter_nearby_connections#7]
<img width="731" alt="image" src="https://user-images.githubusercontent.com/15626305/99346753-685f3f00-28bb-11eb-9dd0-c3f01455e167.png">

**Solution**: Force unwrapping deviceId with '!' solves the problem

**Comment by VNAPNIC** [comment]
I fixed on the https://github.com/VNAPNIC/flutter_nearby_connections/releases/tag/1.0.1-fixbug
