### ISSUE TITLE
Android Crash onMethodCall(FlutterNearbyConnectionsPlugin.kt:88)

### ISSUE THREAD

**Issue by bradintheusa** [VNAPNIC/flutter_nearby_connections#9]
When I run the sample I get this error on Android.   I'm happy to take a look if pointed in the right direction.

[new 2.txt](https://github.com/VNAPNIC/flutter_nearby_connections/files/5579712/new.2.txt)

**Comment by VNAPNIC** [comment]
are u run my example, right?
can you check if there is this code?

`strategy: Strategy.P2P_CLUSTER,`

```
nearbyService.init(
        serviceType: 'mp-connection',
        strategy: Strategy.P2P_CLUSTER,
```

**Comment by bradintheusa** [comment]
I see it and it looks like it gets executed.


```
  void init() async {
    nearbyService = NearbyService();
    await nearbyService.init(
        serviceType: 'mp-connection',
        strategy: Strategy.P2P_CLUSTER,
        callback: (isRunning) async{
```

**Comment by VNAPNIC** [comment]
@bradintheusa fixed : https://github.com/VNAPNIC/flutter_nearby_connections/releases/tag/1.0.6

**Comment by bradintheusa** [comment]
Thanks this has removed the runtime error.
